In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('../../data/spam.csv', encoding='latin-1') # spesifiksi encoding diperlukan karena data tidak menggunakan UTF-8

df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [13]:

# Mengubah label numerik menjadi label teks
df['Labels'] = df['Labels'].map({
    0: 'ham',
    1: 'spam'
})

# Cek jumlah data per kelas
print(df['Labels'].value_counts())
print('\n')

# Cek kelengkapan data
df.info()
print('\n')

# Cek statistik deskriptif
print(df.describe())

Labels
ham     4825
spam     747
Name: count, dtype: int64


<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Labels  5572 non-null   str
 1   SMS     5572 non-null   str
dtypes: str(2)
memory usage: 542.1 KB


       Labels                     SMS
count    5572                    5572
unique      2                    5169
top       ham  Sorry, I'll call later
freq     4825                      30

In [14]:
# Data untuk label
new_labels = {
    'spam': 1,
    'ham': 0
}

# Encode label
df['Labels'] = df['Labels'].map(new_labels)

# Cek data
df.head()

   Labels                                                SMS
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [15]:
X = df['SMS'].values
y = df['Labels'].values

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Pastikan X berupa teks SMS dan y berupa label
X = df['SMS'].astype(str)
y = df['Labels']

# Split data training dan testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=50
)

# Inisiasi CountVectorizer
bow = CountVectorizer()

# Fit dan transform data training
X_train = bow.fit_transform(X_train)

# Transform data testing menggunakan vocabulary training
X_test = bow.transform(X_test)

print("Ukuran X_train:", X_train.shape)
print("Ukuran X_test:", X_test.shape)
print("Ukuran y_train:", y_train.shape)
print("Ukuran y_test:", y_test.shape)

Ukuran X_train: (4457, 7727)
Ukuran X_test: (1115, 7727)
Ukuran y_train: (4457,)
Ukuran y_test: (1115,)

In [20]:

# Menghitung jumlah fitur atau kosakata
print(len(bow.get_feature_names_out()))

# Menampilkan dimensi data training
print(f'Dimensi data: {X_train.shape}')

7727
Dimensi data: (4457, 7727)

In [22]:

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Inisiasi MultinomialNB
mnb = MultinomialNB()

# Fit model dengan data training
mnb.fit(X_train, y_train)

# Prediksi data training
y_pred_train = mnb.predict(X_train)

# Evaluasi akurasi data training
acc_train = accuracy_score(y_train, y_pred_train)

# Prediksi data testing
y_pred_test = mnb.predict(X_test)

# Evaluasi akurasi data testing
acc_test = accuracy_score(y_test, y_pred_test)

# Print hasil evaluasi
print(f'Hasil akurasi data train: {acc_train}')
print(f'Hasil akurasi data test: {acc_test}')

Hasil akurasi data train: 0.9946152120260264
Hasil akurasi data test: 0.9775784753363229